Repository choco-team/FE_TeacherCan, pull requests merged in 2023-05, with the labels that each got.

#30 husky 세팅
  .gitignore
  .gitmessage.txt
  .husky/pre-commit
  .husky/pre-push
  package.json
  src/components/.gitkeep
  src/pages/.gitkeep
  yarn.lock
Labels: setting

#32 vscode setting
  .gitignore
  .vscode/settings.json
Labels: setting

#35 스토리북 alert snackbar 컴포넌트 추가
  README.md
  src/components/Alert/Alert.stories.tsx
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/components/Alert/type.ts
  src/hooks/.gitkeep
  src/hooks/useVisibleTemporarily.ts
Labels: feature

#44 Summary List Component
  src/components/SummaryList/SummaryList.stories.tsx
  src/components/SummaryList/index.tsx
  src/components/SummaryList/style.ts
  src/components/SummaryList/type.ts
  src/components/timerButton/type.ts
  src/styles/darkTheme.ts
  src/styles/lightTheme.ts
  src/styles/skeleton.ts
  src/styles/theme.ts
  src/types/styled-components.d.ts
Labels: feature

#45 WeatherBadge Component
  .eslintrc.json
  src/assets/image/Cloud.png
  src/components/Alert/Alert.stories.tsx
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/components/Alert/type.ts
  src/components/HDButton/HDButton.stories.tsx
  src/components/HDButton/index.tsx
  src/components/HDButton/style.ts
  src/components/HDButton/type.ts
  src/components/JYButton/JYButton.stories.tsx
  src/components/JYButton/index.tsx
  src/components/JYButton/style.ts
  src/components/JYButton/type.ts
  src/components/JYMemo/JYMemo.stories.tsx
  src/components/JYMemo/index.tsx
  src/components/JYMemo/style.ts
  src/components/JYMemo/type.ts
  src/components/WeatherBadge/WeatherBadge.stories.tsx
  src/components/WeatherBadge/index.tsx
  src/components/WeatherBadge/style.ts
  src/components/WeatherBadge/type.ts
  src/components/timerButton/TimerButton.stories.tsx
  src/components/timerButton/index.tsx
  src/components/timerButton/style.ts
  src/components/timerButton/type.ts
  src/styles/skeleton.ts
  src/types/index.d.ts
Labels: feature

#43 로그인 컴포넌트 마크업
  .storybook/preview.tsx
  package.json
  src/Router.tsx
  src/assets/image/icon/kakao.png
  src/components/.gitkeep
  src/constant/routePath.ts
  src/pages/.gitkeep
  src/pages/Auth/AuthInput/Input.stories.tsx
  src/pages/Auth/AuthInput/index.tsx
  src/pages/Auth/AuthInput/style.ts
  src/pages/Auth/AuthInput/type.ts
  src/pages/Auth/SignIn/LinkText/index.tsx
  src/pages/Auth/SignIn/LinkText/style.ts
  src/pages/Auth/SignIn/LinkText/type.ts
  src/pages/Auth/SignIn/SignIn.stories.tsx
  src/pages/Auth/SignIn/SocialSignIn/index.tsx
  src/pages/Auth/SignIn/SocialSignIn/style.ts
  src/pages/Auth/SignIn/index.tsx
  src/pages/Auth/SignIn/style.ts
  src/pages/Auth/index.tsx
  src/pages/Auth/style.ts
  src/styles/GlobalStyle.ts
  src/styles/darkTheme.ts
  src/styles/globalStyle.ts
  src/styles/lightTheme.ts
  src/styles/resetStyle.ts
  src/styles/theme.ts
  src/types/index.d.ts
  src/types/styled-components.d.ts
  yarn.lock
Labels: feature, setting

#49 fix: netlify 404 page not found error
  public/_redirects
Labels: bug

#50 fix: netlify 404 page not found error
  public/_redirects
Labels: bug
