Repository choco-team/FE_TeacherCan, pull requests merged in 2023-09, with the labels that each got.

#121 axios, react query 도입 및 fetch hook 수정
  package.json
  src/api/common.ts
  src/api/school/lunchMenu.ts
  src/hooks/api/useLunchMenu.ts
  src/hooks/query/auth/useAuth.ts
  src/hooks/query/school/useLunchMenu.ts
  src/hooks/query/school/useSchool.ts
  src/pages/App/index.tsx
  src/pages/Auth/AuthInput/index.tsx
  src/pages/Auth/SignIn/index.tsx
  src/pages/Auth/SignUp/index.tsx
  src/pages/ClassManagement/LunchMenu/Menus/index.tsx
  src/pages/ClassManagement/LunchMenu/MenusInformation/type.ts
  src/pages/ClassManagement/LunchMenu/OriginPlaceModal/index.tsx
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/index.tsx
  src/pages/Home/SideSection/index.tsx
  src/types/classManagement/lunchMenu.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feature, setting

#125 fix(Home): SideSection 컴파일 에러 해결
  src/Router.tsx
  src/pages/Home/SideSection/index.tsx
Labels: bug

#127 [FE] fetch 부분 react-query 적용
  .eslintrc.json
  package.json
  public/mockServiceWorker.js
  src/Router.tsx
  src/api/auth/auth.ts
  src/api/school/lunchMenu.ts
  src/api/school/search.ts
  src/api/user/user.ts
  src/hooks/query/auth/useAuth.ts
  src/hooks/query/school/useLunchMenu.ts
  src/hooks/query/school/useSchool.ts
  src/main.tsx
  src/pages/App/index.tsx
  src/pages/Auth/AuthInput/index.tsx
  src/pages/Auth/AuthInput/type.ts
  src/pages/Auth/SignIn/index.tsx
  src/pages/Auth/SignUp/index.tsx
  src/pages/ClassManagement/.gitkeep
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/PagiNationButton/index.tsx
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/PagiNationButton/type.ts
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/SearchResult/index.tsx
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/SearchResult/type.ts
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/index.tsx
  src/pages/ClassManagement/LunchMenu/RegisterSchoolModal/style.ts
  src/providers/UserProvider/index.tsx
  src/types/classManagement/lunchMenu.ts
  src/types/classManagement/school.ts
  yarn.lock
Labels: refactor
